url: 'https://olumentary.com'
baseurl: ''
title: 'olumentary'
description: 

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - .nvmrc
  - .ruby-version
  - README.md